<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>SDDC_DEPLOY_MSG</string>
	</array>
	<key>name</key>
	<string>SDDC Deploy Message</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.sddc-commit.branch</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*# On branch (.*)\n</string>
			<key>name</key>
			<string>comment.line.number-sign.sddc-commit</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.sddc-commit</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.sddc-commit.remote.ahead</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.other.sddc-commit.remote.name</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.other.sddc-commit.remote.ahead</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.other.sddc-commit.remote.num-commits</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\s*# Your branch is )(ahead of ')(.+)(' by )(\d+ .+)\.\n</string>
			<key>name</key>
			<string>meta.sddc-commit.remote.status</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.other.sddc-commit.header</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*# (Changes to be committed:)</string>
			<key>name</key>
			<string>comment.line.number-sign.sddc-commit</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.other.sddc-commit.header</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*# (Changes not staged for commit:)</string>
			<key>name</key>
			<string>comment.line.number-sign.sddc-commit</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.other.sddc-commit.header</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*# (Untracked files:)</string>
			<key>name</key>
			<string>comment.line.number-sign.sddc-commit</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.deleted.warning.sddc-commit</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*# (warning:.+)</string>
			<key>name</key>
			<string>comment.line.number-sign.sddc-commit</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.sddc-commit</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.other.sddc-commit.status</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.sddc-commit</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.other.sddc-commit.file</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*((?:#   )|(?:#	))(.+:)(\s+)(.+)</string>
			<key>name</key>
			<string>meta.sddc-commit.line</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*#(.*)</string>
			<key>name</key>
			<string>comment.line.number-sign.sddc-commit</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.sddc-diff</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.sddc-commit</string>
	<key>uuid</key>
	<string>b63359ca-26c8-11e8-9b5b-801934191b2b</string>
</dict>
</plist>
